import React, {useState } from 'react';
import { Archive, Award, BarChart3, CheckCircle2, Download, FileText, Lock, Monitor, Palette, Radio, ShieldCheck, Trophy, Users, Wifi, XCircle } from 'lucide-react';
import { useAccessControl } from '@/context/AccessControlContext';
import { getAuditLog, logAudit } from '@/lib/audit-log';
import { buildTournamentPackage, downloadJson, loadFeatureMatches, loadMatRules, saveFeatureMatches } from '@/lib/feature-complete';
import { buildAwards, getTournamentPerformanceRows } from '@/lib/tournament-intelligence';

type Tab = 'BROADCAST'|'REPORTS'|'AWARDS'|'ARCHIVE'|'SECURITY'|'SYSTEM';
const tabs:Tab[]=['BROADCAST','REPORTS','AWARDS','ARCHIVE','SECURITY','SYSTEM'];
const card='rounded-2xl border border-white/10 bg-white/[0.035] p-4';
const KEY='wab-tkd-final-command-v1';
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function metric(matches:any[], field:string){return matches.reduce((n,m)=>n+(Number(m[field])||0),0)}
export default function FinalCommandCenterPage(){
 const {role,userName,isSupervisor,isAdmin,canExport,lock}=useAccessControl();
 const [tab,setTab]=useState<Tab>('BROADCAST');
 const [state,setState]=useState<any>(loadState());
 const [selected,setSelected]=useState('');
 const matches=React.useMemo(()=>loadFeatureMatches(),[]);
 const rules=React.useMemo(()=>loadMatRules(),[]);
 const audits=React.useMemo(()=>getAuditLog().slice(-20).reverse(),[]);
 const calculatedAwards=React.useMemo(()=>buildAwards(getTournamentPerformanceRows()),[]);
 const live=matches.filter(m=>m.status==='LIVE'); const ready=matches.filter(m=>m.status==='READY'); const completed=matches.filter(m=>m.status==='COMPLETED');
 const current=live[0]||ready[0]||completed[completed.length-1];
 const save=(patch:any)=>{const next={...state,...patch};setState(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const exportPackage=()=>{if(!canExport)return;downloadJson('WAB-TKD-FINAL-TOURNAMENT-PACKAGE.json',buildTournamentPackage({matches,matRules:rules,auditLog:getAuditLog(),awards:state.awards||{},broadcast:state.broadcast||{},archive:state.archive||{},finalized:state.finalized||false}));logAudit('FINAL_PACKAGE_EXPORT',{user:userName});};
 const finalize=()=>{if(!isSupervisor)return;save({finalized:true,finalizedAt:new Date().toISOString(),finalizedBy:userName});logAudit('TOURNAMENT_FINALIZED',{user:userName});};
 const reopen=()=>{if(!isAdmin)return;save({finalized:false,reopenedAt:new Date().toISOString(),reopenedBy:userName});logAudit('TOURNAMENT_REOPENED',{user:userName});};
 const selectMatch=(id:string)=>setSelected(id);
 const selectedMatch=matches.find(m=>m.id===selected)||current;
 return <div className="min-h-screen bg-background text-foreground p-4 md:p-6 space-y-5">
  
  <header className="flex flex-col xl:flex-row xl:items-center xl:justify-between gap-4">
   <div><div className="text-[10px] tracking-[.3em] font-black text-yellow-400">WAB-TKD • FINAL COMMAND CENTER</div><h1 className="text-3xl md:text-4xl font-black mt-1">TOURNAMENT • BROADCAST • ARCHIVE</h1><p className="text-xs text-muted-foreground mt-2">Final operating layer over V35. Control remains separated from public output.</p></div>
   <div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="px-3 py-2 rounded-lg bg-emerald-500/10 text-emerald-400"><Wifi className="inline w-3 h-3 mr-1"/> DATABASE ONLINE</span><span className="px-3 py-2 rounded-lg bg-blue-500/10 text-blue-300"><Monitor className="inline w-3 h-3 mr-1"/> PUBLIC CONNECTED</span><span className="px-3 py-2 rounded-lg bg-white/5">{role} • {userName||'OPERATOR'}</span></div>
  </header>
  <div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[['LIVE',live.length],['NEXT',ready.length],['COMPLETED',completed.length],['MATS',new Set(matches.map(m=>m.mat).filter(Boolean)).size],['AUDIT',audits.length],['FINALIZED',state.finalized?'YES':'NO']].map(([l,v])=><div className={card} key={String(l)}><div className="text-[9px] font-black text-muted-foreground">{l}</div><div className="text-xl md:text-2xl font-black mt-1">{v}</div></div>)}</div>
  <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-lg text-[10px] font-black whitespace-nowrap ${tab===t?'bg-yellow-500 text-black':'bg-white/5 text-white'}`}>{t}</button>)}</div>

  {tab==='BROADCAST'&&<div className="grid xl:grid-cols-3 gap-4">
   <div className={card+' xl:col-span-2'}><div className="flex items-center justify-between"><h2 className="font-black flex gap-2"><Radio className="w-4 h-4"/> BROADCAST DIRECTOR</h2><span className="text-[9px] font-black text-emerald-400">OUTPUT: PUBLIC DISPLAY</span></div>
    <div className="grid md:grid-cols-2 gap-3 mt-4">{[['PLAYER CALL','PLAYER_CALL'],['MATCHUP','MATCHUP'],['VICTORY','VICTORY'],['MVP','MVP'],['BEST PLAYER','BEST_PLAYER'],['TEAM VICTORY','TEAM_VICTORY'],['PODIUM','PODIUM']].map(([label,cmd])=><button key={cmd} onClick={()=>{save({broadcast:{command:cmd,at:new Date().toISOString(),matchId:selectedMatch?.id||null}});logAudit('BROADCAST_COMMAND',{command:cmd,matchId:selectedMatch?.id,user:userName})}} className="rounded-xl border border-white/10 bg-black/20 hover:bg-yellow-500/10 p-4 text-left"><div className="text-[10px] text-muted-foreground">BROADCAST</div><div className="font-black mt-1">{label}</div></button>)}</div>
   </div>
   <div className={card}><h2 className="font-black flex gap-2"><Monitor className="w-4 h-4"/> LIVE OUTPUT</h2><div className="mt-4 rounded-2xl border border-yellow-500/20 bg-gradient-to-br from-black via-yellow-500/[.04] to-black p-5 min-h-[220px]"><div className="text-[9px] tracking-[.25em] text-yellow-400 font-black">WAB-TKD • BROADCAST</div><div className="text-2xl font-black mt-4">{state.broadcast?.command||'READY'}</div><div className="mt-4 text-sm">MAT {selectedMatch?.mat?String(selectedMatch.mat).padStart(2,'0'):'—'} • MATCH #{selectedMatch?.number||'—'}</div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-blue-500/10 p-3">BLUE<br/><b>{selectedMatch?.blue||'—'}</b></div><div className="rounded-lg bg-red-500/10 p-3">RED<br/><b>{selectedMatch?.red||'—'}</b></div></div></div></div>
   <div className={card+' xl:col-span-3'}><h2 className="font-black">SELECT MATCH / REAL DATA SOURCE</h2><div className="grid md:grid-cols-3 xl:grid-cols-5 gap-2 mt-3">{matches.slice(0,15).map(m=><button key={m.id} onClick={()=>selectMatch(m.id)} className={`p-3 rounded-xl text-left border ${selectedMatch?.id===m.id?'border-yellow-400 bg-yellow-500/10':'border-white/10 bg-white/[.02]'}`}><div className="text-[9px] text-muted-foreground">#{m.number} • MAT {m.mat||'—'}</div><div className="text-xs font-black mt-1">{m.blue} vs {m.red}</div><div className="text-[9px] mt-1">{m.weight} • {m.round}</div></button>)}</div></div>
  </div>}

  {tab==='REPORTS'&&<div className="grid lg:grid-cols-2 gap-4"><div className={card}><h2 className="font-black flex gap-2"><BarChart3 className="w-4 h-4"/> TOURNAMENT REPORT</h2><div className="grid grid-cols-2 gap-3 mt-4">{[['Matches',matches.length],['Completed',completed.length],['Live',live.length],['Ready',ready.length],['Assigned Mats',new Set(matches.map(m=>m.mat).filter(Boolean)).size],['Audit Events',getAuditLog().length]].map(([a,b])=><div className="rounded-xl bg-white/[.025] p-4" key={String(a)}><div className="text-[9px] text-muted-foreground">{a}</div><div className="text-2xl font-black mt-1">{b}</div></div>)}</div><button onClick={()=>downloadJson('WAB-TKD-TOURNAMENT-REPORT.json',{generatedAt:new Date().toISOString(),matches,matRules:rules,summary:{total:matches.length,completed:completed.length,live:live.length,ready:ready.length}})} className="mt-4 px-4 py-3 rounded-xl bg-white/10 font-black text-xs"><FileText className="inline w-4 h-4 mr-2"/> EXPORT REPORT</button></div><div className={card}><h2 className="font-black flex gap-2"><Users className="w-4 h-4"/> PLAYER / TEAM REPORT</h2><p className="text-xs text-muted-foreground mt-2">Uses the existing match ledger and keeps V35 judging as the source of truth.</p><div className="space-y-2 mt-4">{completed.slice(-8).reverse().map(m=><div key={m.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3 text-xs"><span>#{m.number} • {m.blue} vs {m.red}</span><b>{m.winner||'RESULT PENDING'}</b></div>)}</div></div></div>}

  {tab==='AWARDS'&&<div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-3 rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-4 flex flex-wrap items-center justify-between gap-3"><div><div className="font-black text-sm">CALCULATED AWARDS</div><div className="text-[10px] text-muted-foreground mt-1">Derived from the Performance Ledger. Manual names are no longer required for final publication.</div></div><button disabled={!isSupervisor&&!isAdmin} onClick={()=>{const awards=Object.fromEntries(calculatedAwards.map(a=>[a.key,a.winner]));save({awards,awardsCalculatedAt:new Date().toISOString(),awardsCalculatedBy:userName});logAudit('AWARDS_CONFIRMED',{user:userName,source:'PERFORMANCE_LEDGER',count:calculatedAwards.length});}} className="px-4 py-3 rounded-xl bg-yellow-500 text-black text-[10px] font-black disabled:opacity-30">CONFIRM CALCULATED AWARDS</button></div>{calculatedAwards.map((a:any)=><div className={card} key={a.key}><Award className="w-5 h-5 text-yellow-400"/><div className="text-[9px] tracking-widest text-muted-foreground mt-3">AWARD</div><h3 className="font-black mt-1">{a.title}</h3><div className="mt-3 rounded-lg bg-black/20 border border-white/10 p-3"><div className="text-sm font-black">{a.winner}</div><div className="text-[9px] text-muted-foreground mt-1">SCORE {a.score}</div></div><div className="text-[9px] text-muted-foreground mt-2">{a.reason}</div></div>)}{calculatedAwards.length===0&&<div className="lg:col-span-3 rounded-xl border border-white/10 p-5 text-xs text-muted-foreground">No Performance Ledger data is available yet. Awards cannot be fabricated or manually published from this screen.</div>}</div>}

  {tab==='ARCHIVE'&&<div className="grid lg:grid-cols-3 gap-4"><div className={card+' lg:col-span-2'}><h2 className="font-black flex gap-2"><Archive className="w-4 h-4"/> FINAL ARCHIVE</h2><p className="text-xs text-muted-foreground mt-2">Finalization creates an immutable operating state for the tournament layer. V35 data is never overwritten.</p><div className="mt-4 rounded-xl border border-white/10 p-4"><div className="text-[10px]">STATUS</div><div className={`text-2xl font-black mt-1 ${state.finalized?'text-emerald-400':'text-yellow-400'}`}>{state.finalized?'FINALIZED':'OPEN'}</div>{state.finalized&&<div className="text-[9px] text-muted-foreground mt-2">By {state.finalizedBy} • {state.finalizedAt}</div>}</div><div className="flex flex-wrap gap-2 mt-4"><button disabled={!isSupervisor||state.finalized} onClick={finalize} className="px-4 py-3 rounded-xl bg-emerald-500 text-black text-xs font-black disabled:opacity-30"><CheckCircle2 className="inline w-4 h-4 mr-2"/> FINALIZE</button><button disabled={!isAdmin||!state.finalized} onClick={reopen} className="px-4 py-3 rounded-xl bg-white/10 text-xs font-black disabled:opacity-30"><XCircle className="inline w-4 h-4 mr-2"/> ADMIN REOPEN</button><button onClick={exportPackage} className="px-4 py-3 rounded-xl bg-yellow-500 text-black text-xs font-black"><Download className="inline w-4 h-4 mr-2"/> EXPORT COMPLETE PACKAGE</button></div></div><div className={card}><Trophy className="w-5 h-5 text-yellow-400"/><h3 className="font-black mt-3">ARCHIVE CONTENT</h3><ul className="text-xs text-muted-foreground mt-3 space-y-2"><li>✓ Results & Bracket</li><li>✓ Player / Team references</li><li>✓ Mat assignments</li><li>✓ Rankings / Awards</li><li>✓ Audit Trail</li><li>✓ Final snapshots</li></ul></div></div>}

  {tab==='SECURITY'&&<div className="grid lg:grid-cols-2 gap-4"><div className={card}><h2 className="font-black flex gap-2"><ShieldCheck className="w-4 h-4"/> PROTECTED OPERATIONS</h2><div className="space-y-2 mt-4">{[['REFEREE','Operate / Score / Call'],['SUPERVISOR','Restore / Finalize / Emergency'],['ADMIN','Users / Override / Reopen / System']].map(([r,p])=><div className="rounded-xl border border-white/10 p-3" key={r}><b>{r}</b><div className="text-xs text-muted-foreground mt-1">{p}</div></div>)}</div></div><div className={card}><h2 className="font-black flex gap-2"><Lock className="w-4 h-4"/> AUDIT TRAIL</h2><div className="space-y-2 mt-4 max-h-[350px] overflow-auto">{audits.map((a:any,i)=><div className="rounded-lg bg-white/[.025] p-3 text-[10px]" key={i}><b>{a.action||a.event||'EVENT'}</b><div className="text-muted-foreground mt-1">{a.user||a.actor||userName||'SYSTEM'} • {a.at||a.timestamp||''}</div></div>)}</div></div></div>}

  {tab==='SYSTEM'&&<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{[['DATABASE','ONLINE',true],['PUBLIC DISPLAY','CONNECTED',true],['AUTO SAVE','ACTIVE',true],['V35 SOURCE OF TRUTH','LOCKED',true],['BROADCAST OUTPUT','READY',true],['MAT ASSIGNMENT','ACTIVE',true],['AUDIT TRAIL','ACTIVE',true],['ARCHIVE','READY',true]].map(([a,b,ok])=><div className={card} key={String(a)}><div className="text-[9px] text-muted-foreground">{a}</div><div className={`text-xl font-black mt-2 ${ok?'text-emerald-400':'text-red-400'}`}>{b}</div></div>)}</div>}

  <footer className="text-[9px] text-muted-foreground flex flex-wrap gap-4 items-center"><span><Palette className="inline w-3 h-3 mr-1"/> WAB-TKD broadcast identity preserved</span><span>V35 remains the match truth source</span><span>Control ≠ Public Output</span>{state.finalized&&<span className="text-emerald-400">FINAL ARCHIVE LOCKED</span>}</footer>
 </div>
}
