import React, {useState} from 'react';
import { CheckCircle2, ClipboardCheck, LockKeyhole, RefreshCw, ShieldAlert, Monitor, Trophy, Download } from 'lucide-react';
import { useAccessControl } from '@/context/AccessControlContext';
import { QA_SUITES, QATestStatus, summarize, isReleaseReady, runAutomatedSuite } from '@/lib/qa-center';
import { runLocalReadiness } from '@/lib/release-readiness';

const key='wab-qa-results-v1';
function load():Record<string,QATestStatus>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
export default function QATestCenterPage(){
 const {role,userName}=useAccessControl(); const [results,setResults]=useState<Record<string,QATestStatus>>(load); const [running,setRunning]=useState(false);
 const summary=React.useMemo(()=>summarize(results),[results]); const ready=isReleaseReady(results); const readiness=React.useMemo(()=>runLocalReadiness(results),[results]);
 const set=(id:string,status:QATestStatus)=>{const next={...results,[id]:status};setResults(next);localStorage.setItem(key,JSON.stringify(next));};
 const runAll=()=>{setRunning(true); setTimeout(()=>{const next={...results}; QA_SUITES.forEach(s=>{ next[s.id]=runAutomatedSuite(s.id).status; }); setResults(next); localStorage.setItem(key,JSON.stringify(next)); setRunning(false)},80)};
 const exportReport=()=>{const report={product:'WAB-TKD',generatedAt:new Date().toISOString(),operator:userName||role,summary,releaseReady:ready,suites:QA_SUITES.map(s=>({...s,status:results[s.id]||'NOT_RUN'}))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download=`wab-tkd-qa-report-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="ops-pro" dir="ltr"><header className="ops-pro-header"><div><div className="ops-eyebrow">WAB-TKD • QA / TEST CENTER</div><h1>Final QA & Recovery Center</h1><p>Controlled test matrix for tournament operations. This page does not alter V35 judging or match results.</p></div><div className="ops-head-actions"><button className="ops-btn ghost" onClick={runAll}><RefreshCw size={15}/>{running?'Preparing…':'Run Test Matrix'}</button><button className="ops-btn ghost" onClick={exportReport}><Download size={15}/>Export QA Report</button></div></header>
 <section className="ops-health"><Health label="ROLE" value={role} ok/><Health label="CRITICAL" value={`${QA_SUITES.filter(s=>s.severity==='CRITICAL').length} suites`} ok/><Health label="PASS" value={`${summary.pass}/${summary.total}`} ok={summary.fail===0}/><Health label="FAIL" value={String(summary.fail)} ok={summary.fail===0}/><Health label="BLOCKED" value={String(summary.blocked)} ok={summary.blocked===0}/><Health label="RELEASE" value={ready?'READY':'NOT READY'} ok={ready}/><Health label="LOCAL" value={readiness.ready?'READY':'CHECK'} ok={readiness.ready}/></section>
 <main className="ops-section"><section className="ops-card"><div className="ops-card-title"><span><ClipboardCheck/></span><div><h2>Test Matrix</h2><p>Run each scenario on the real deployment before tournament use. Status is saved locally on this operator station.</p></div></div><div className="qa-grid">{QA_SUITES.map(s=><article className="qa-card" key={s.id}><div className="qa-top"><span className={`qa-severity ${s.severity.toLowerCase()}`}>{s.severity}</span><span className={`qa-status ${String(results[s.id]||'NOT_RUN').toLowerCase()}`}>{results[s.id]||'NOT_RUN'}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="qa-tags">{s.tags.map(t=><span key={t}>{t}</span>)}</div><div className="qa-actions"><button className="qa-auto" onClick={()=>{const r=runAutomatedSuite(s.id);set(s.id,r.status);}}><RefreshCw size={15}/>Auto Check</button><button onClick={()=>set(s.id,'PASS')}><CheckCircle2 size={15}/>Pass</button><button onClick={()=>set(s.id,'FAIL')}><ShieldAlert size={15}/>Fail</button><button onClick={()=>set(s.id,'BLOCKED')}><LockKeyhole size={15}/>Blocked</button><button onClick={()=>set(s.id,'NOT_RUN')}>Reset</button></div></article>)}</div></section>
 <section className="ops-card"><div className="ops-card-title"><span><Trophy/></span><div><h2>Release Gate</h2><p>All critical and non-critical suites must be PASS before calling the deployment tournament-ready.</p></div></div><div className="permission-grid"><Metric label="TOTAL" value={summary.total}/><Metric label="PASS" value={summary.pass}/><Metric label="FAIL" value={summary.fail}/><Metric label="BLOCKED" value={summary.blocked}/><Metric label="NOT RUN" value={summary.notRun}/><Metric label="RELEASE" value={ready?'READY':'NOT READY'}/></div><div className="qa-note"><Monitor size={16}/><span>{readiness.checks.filter(c=>!c.ok).length ? `Local readiness: ${readiness.checks.filter(c=>!c.ok).map(c=>c.label).join(', ')}` : 'Local readiness probes are clear.'}</span></div><div className="qa-note"><Monitor size={16}/> Recommended run order: authentication → match flow → Par Équipe recovery → Multi-Mat → displays → statistics/MVP → export/history → emergency recovery.</div></section></main>
 </div>
}
function Health({label,value,ok}:{label:string,value:string,ok:boolean}){return <div className="ops-health-item"><small>{label}</small><b className={ok?'ok':'bad'}>● {value}</b></div>}
function Metric({label,value}:{label:string,value:string|number}){return <div className="ops-metric"><small>{label}</small><b>{value}</b></div>}
