import React, {useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Activity, Award, BarChart3, Download, GitBranch, Lock, Monitor, Pause, Radio, RefreshCw, ShieldAlert, ShieldCheck, Trophy, Users, Zap } from 'lucide-react';
import { useMatch } from '@/context/MatchContext';
import { useAccessControl } from '@/context/AccessControlContext';
import { getAuditLog, logAudit } from '@/lib/audit-log';
import { getCountryFlag } from '@/lib/flags';
import { fetchAllMatStatuses, getMatCount, MatLiveStatus } from '@/lib/mat-status';
import { listQueuedMatches, MatQueuedMatch } from '@/lib/mat-queue';
import { loadAllLocalTournaments } from '@/lib/tournament-local';
import { toast } from 'sonner';
import { getPendingSyncActions, isOnline } from '@/lib/offline-sync';
import TournamentUsersPanel from '@/components/TournamentUsersPanel';
import { calculateMvp, buildAwards, aggregatePlayers, scoreMatchPlayer, PlayerPerformance, recordMatchPerformance, getTournamentPerformanceRows } from '@/lib/tournament-intelligence';

const tabs = ['CONTROL','BROADCAST','TEAM MANAGER','LIVE STATS','RANKINGS','AWARDS','GRAPHICS','EXPORT','EMERGENCY','USERS','HEALTH'] as const;
type Tab = typeof tabs[number];

function metric(label:string,value:React.ReactNode,sub?:string){return <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="text-[9px] text-muted-foreground font-black tracking-wider">{label}</div><div className="text-2xl font-display font-black mt-1">{value}</div>{sub&&<div className="text-[9px] text-muted-foreground mt-1">{sub}</div>}</div>}

export default function TournamentIntelligencePage(){
  const { state, dispatch } = useMatch();
  const { role, userName, isSupervisor, isAdmin, canExport } = useAccessControl();
  const navigate = useNavigate();
  const [tab,setTab]=useState<Tab>('CONTROL');
  const [mats,setMats]=useState<MatLiveStatus[]>([]);
  const [queue,setQueue]=useState<MatQueuedMatch[]>([]);
  const [emergency,setEmergency]=useState(false);
  const [broadcast,setBroadcast]=useState('NEXT MATCH');

  const refresh = async()=>{setMats(await fetchAllMatStatuses());setQueue(await listQueuedMatches());};
  React.useEffect(()=>{refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id)},[]);

  const stats=React.useMemo(()=>{
    const ev=state.events||[]; const score={chung:0,hong:0}; const hits={chung:0,hong:0}; const head={chung:0,hong:0}; const body={chung:0,hong:0};
    ev.forEach(e=>{score[e.player]+=e.points; if(e.type!=='gamjeom'){hits[e.player]++; if(e.type==='head_kick'||e.type==='turning_head')head[e.player]++; else body[e.player]++;}});
    const warnings=ev.filter(e=>e.type==='gamjeom').length;
    const rounds=state.roundWinners?.length||0;
    const winner=state.result?.winner;
    const perf=(side:'chung'|'hong')=>Math.max(0,Math.min(100,50 + (score[side]-score[side==='chung'?'hong':'chung'])*3 + hits[side]*2 - (side===winner?0:5)));
    return {score,hits,head,body,warnings,rounds,winner,perf};
  },[state.events,state.roundWinners,state.result]);

  const teamScore={blue:state.teamNames?.chung||'BLUE',red:state.teamNames?.hong||'RED'};
  const liveCount=mats.filter(m=>m.status==='running').length;
  const available=mats.filter(m=>m.status==='idle'&&!m.locked&&m.online!==false).length;
  const completed=state.result?1:0;
  const localTournaments=loadAllLocalTournaments();

  const performanceRows = useMemo<PlayerPerformance[]>(()=>{
    const base = (['chung','hong'] as const).map(side=>{
      const own = side==='chung' ? state.chung.player : state.hong.player;
      const other = side==='chung' ? state.hong.player : state.chung.player;
      const scored = scoreMatchPlayer(state.events||[], side, side==='chung'?'hong':'chung', state.result);
      return { ...scored, id:own.id, name:own.name, nationality:own.nationality, club:own.club, team:state.teamNames?.[side], matches:1, wins:state.result?.winner===side?1:0, losses:state.result&&state.result.winner!==side?1:0, pointsFor:stats.score[side], pointsAgainst:stats.score[side==='chung'?'hong':'chung'], pointDiff:stats.score[side]-stats.score[side==='chung'?'hong':'chung'], hits:stats.hits[side], headHits:stats.head[side], bodyHits:stats.body[side], warnings:stats.warnings, penalties:stats.warnings, fairPlay:Math.max(0,100-stats.warnings*8), rounds:Math.max(1,stats.rounds), roundWins:state.roundWinners?.filter(r=>r.winner===side).length||0, scoringEfficiency:stats.hits[side]?Math.min(100,(stats.score[side]/(stats.hits[side]*5))*100):0, consistency:Math.max(0,100-Math.abs(stats.score[side]-stats.score[side==='chung'?'hong':'chung'])/Math.max(1,stats.score[side]+stats.score[side==='chung'?'hong':'chung'])*100), opponentStrength:50+Math.min(35,stats.score[side==='chung'?'hong':'chung']*1.5), performanceScore:stats.perf(side), contributionScore:stats.perf(side) };
    });
    return aggregatePlayers(base);
  },[state,stats]);
  const mvp = React.useMemo(()=>calculateMvp(performanceRows),[performanceRows]);
  const awards = React.useMemo(()=>buildAwards(performanceRows),[performanceRows]);
  React.useEffect(()=>{ if(state.result && state.id) recordMatchPerformance(String(state.id),performanceRows); },[state.result,state.id,performanceRows]);
  const tournamentRows = React.useMemo(()=>{ const stored=getTournamentPerformanceRows(); return stored.length?stored:performanceRows; },[performanceRows,state.result]);

  const exportTournament=()=>{
    if(!canExport)return;
    const payload={exportVersion:'WAB-TKD-INTELLIGENCE-PRO-2',exportedAt:new Date().toISOString(),actor:userName,role,currentMatch:state,tournaments:localTournaments,matStatuses:mats,queuedMatches:queue,auditLog:getAuditLog(),rankings:tournamentRows,awards,systemHealth:{database:'ONLINE',autoSave:'ACTIVE',publicDisplay:'CONNECTED',mats:mats.map(m=>({mat:m.mat_number,online:m.online,locked:m.locked,device:m.device_name}))},snapshots:{current:state}};
    const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a');a.href=url;a.download=`WAB-TKD-Tournament-Package-${Date.now()}.json`;a.click();URL.revokeObjectURL(url);logAudit('tournament_export','Tournament intelligence package exported');toast.success('Tournament package exported');
  };
  const emergencyPause=()=>{if(!isSupervisor)return; dispatch({type:'PAUSE'}); setEmergency(true); logAudit('emergency_pause','Emergency pause requested from Tournament Intelligence'); toast.warning('EMERGENCY PAUSE ACTIVE');};
  const resume=()=>{if(!isSupervisor)return;dispatch({type:'RESUME'});setEmergency(false);logAudit('emergency_resume','Emergency resume from Tournament Intelligence');};
  const lockMatch=()=>{if(!isSupervisor)return;dispatch({type:'PAUSE'});setEmergency(true);logAudit('match_lock','Current match locked by supervisor');toast.warning('MATCH LOCKED');};

  return <div className="min-h-screen bg-background text-foreground p-3 md:p-5">
  
    <div className="max-w-[1600px] mx-auto space-y-3">
      <header className="panel p-4 flex flex-col lg:flex-row gap-3 lg:items-center lg:justify-between">
        <div><div className="text-[10px] tracking-[0.25em] text-[hsl(var(--gold))] font-black">WAB-TKD · TOURNAMENT INTELLIGENCE</div><h1 className="text-2xl md:text-3xl font-display font-black">Tournament Command Center</h1><div className="text-[10px] text-muted-foreground mt-1">Live tournament control · broadcast · statistics · awards · recovery</div></div>
        <div className="flex items-center gap-2 text-[9px] font-black"><span className="px-2 py-1 rounded bg-emerald-500/10 text-emerald-300">DB ONLINE</span><span className="px-2 py-1 rounded bg-emerald-500/10 text-emerald-300">AUTO SAVE ACTIVE</span><span className="px-2 py-1 rounded bg-[hsl(var(--gold))]/10 text-[hsl(var(--gold))]">{role}</span></div>
      </header>
      <div className="flex gap-1 overflow-x-auto pb-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-lg text-[9px] font-black whitespace-nowrap ${tab===t?'bg-[hsl(var(--gold))] text-black':'bg-white/5 text-muted-foreground'}`}>{t}</button>)}</div>

      {tab==='CONTROL'&&<>
        <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-2">{metric('LIVE MATS',liveCount)}{metric('AVAILABLE',available)}{metric('QUEUED',queue.length)}{metric('CURRENT MATCH',state.matchNumber??'—')}{metric('MAT',state.matNumber?`MAT ${String(state.matNumber).padStart(2,'0')}`:'—')}{metric('ROUND',state.currentRound)}{metric('COMPLETED',completed)}{metric('MATS',getMatCount())}</div>
        <div className="grid lg:grid-cols-3 gap-3">
          <section className="panel p-4 lg:col-span-2"><div className="flex justify-between items-center mb-3"><h2 className="font-display font-black text-sm text-[hsl(var(--gold))]">LIVE MAT CONTROL</h2><button onClick={refresh} className="p-2 rounded bg-white/5"><RefreshCw size={13}/></button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-2">{mats.map(m=><div key={m.mat_number} className="rounded-xl border border-white/10 p-3 bg-black/10"><div className="flex justify-between"><span className="font-black text-[hsl(var(--gold))]">MAT {String(m.mat_number).padStart(2,'0')}</span><span className={`text-[8px] font-black ${m.locked||m.online===false?'text-red-300':'text-emerald-300'}`}>{m.locked?'LOCKED':m.online===false?'OFFLINE':m.status.toUpperCase()}</span></div><div className="mt-2 text-[10px] font-bold">{m.chung_name||'—'} <span className="text-muted-foreground">vs</span> {m.hong_name||'—'}</div><div className="text-[8px] text-muted-foreground mt-1">{m.weight_category||'—'} · {m.match_stage||'—'} · #{m.match_number||'—'}</div><div className="text-[8px] text-muted-foreground mt-2">🖥 {m.device_name||'NO DEVICE'}</div></div>)}</div></section>
          <section className="panel p-4"><h2 className="font-display font-black text-sm text-[hsl(var(--gold))] mb-3">CURRENT MATCH</h2><div className="rounded-xl border border-white/10 p-4 bg-black/20"><div className="text-[9px] text-muted-foreground">{state.competitionName||'WAB-TKD'} · MAT {state.matNumber||'—'}</div><div className="mt-3 text-lg font-black text-blue-300">{getCountryFlag(state.chung.player.nationality)} {state.chung.player.name}</div><div className="text-center text-[9px] text-muted-foreground py-1">{state.chung.totalScore} — {state.hong.totalScore}</div><div className="text-lg font-black text-red-300">{getCountryFlag(state.hong.player.nationality)} {state.hong.player.name}</div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>navigate('/operator')} className="py-2 rounded bg-[hsl(var(--gold))] text-black text-[9px] font-black">MAIN REFEREE</button><button onClick={()=>navigate('/tournament-wall')} className="py-2 rounded bg-white/5 text-[9px] font-black">PUBLIC WALL</button></div></div></section>
        </div>
      </>}

      {tab==='BROADCAST'&&<section className="panel p-4"><div className="flex justify-between items-center mb-4"><div><h2 className="font-display font-black text-sm text-[hsl(var(--gold))]">BROADCAST DIRECTOR</h2><p className="text-[9px] text-muted-foreground">Central director · Public Display remains output-only</p></div><Radio size={18} className="text-[hsl(var(--gold))]"/></div><div className="grid md:grid-cols-3 gap-3">{['PLAYER CALL','MATCHUP','VICTORY','MVP','REPLAY','NEXT MATCH'].map(x=><button key={x} onClick={()=>{setBroadcast(x);logAudit('broadcast_command',x);toast.success(`${x} queued`)}} className={`p-4 rounded-xl border text-left ${broadcast===x?'border-[hsl(var(--gold))] bg-[hsl(var(--gold))]/10':'border-white/10 bg-white/[0.03]'}`}><div className="font-black text-xs">{x}</div><div className="text-[9px] text-muted-foreground mt-1">Uses current match data</div></button>)}</div><div className="mt-4 rounded-xl border border-[hsl(var(--gold))]/20 p-4 bg-[hsl(var(--gold))]/5"><div className="text-[9px] font-black text-[hsl(var(--gold))]">DIRECTOR STATE</div><div className="text-2xl font-display font-black mt-1">{broadcast}</div><div className="text-[9px] text-muted-foreground mt-1">Control: Main Referee · Output: Public Display / Tournament Wall</div></div></section>}

      {tab==='TEAM MANAGER'&&<section className="panel p-4"><div className="flex justify-between items-center mb-4"><div><h2 className="font-display font-black text-sm text-[hsl(var(--gold))]">PAR ÉQUIPE · TEAM MATCH MANAGER</h2><p className="text-[9px] text-muted-foreground">Roster order · pending/active/completed · progress</p></div><Users size={18} className="text-[hsl(var(--gold))]"/></div><div className="grid md:grid-cols-2 gap-4">{(['chung','hong'] as const).map(side=>{const roster=state.teamRoster?.[side]||[];return <div key={side} className="rounded-xl border border-white/10 p-3"><div className={`font-black text-sm ${side==='chung'?'text-blue-300':'text-red-300'}`}>{side==='chung'?teamScore.blue:teamScore.red}</div><div className="text-[9px] text-muted-foreground mb-2">{roster.length} PLAYERS</div>{roster.map((p,i)=><div key={`${p.name}-${i}`} className="flex items-center gap-2 py-2 border-t border-white/5"><span className="w-6 h-6 rounded bg-white/5 grid place-items-center text-[9px] font-black">{i+1}</span><div className="flex-1"><div className="text-[10px] font-bold">{p.name}</div><div className="text-[8px] text-muted-foreground">{p.playerNumber??'—'} · {p.nationality}</div></div><span className="text-[8px] font-black">{p.roundScores?.length?'COMPLETED':'PENDING'}</span></div>)}</div>})}</div><div className="mt-4 grid grid-cols-3 gap-2">{metric('PROGRESS',`${Math.min(state.roundWinners?.length||0,state.teamRoster?.chung?.length||0)} / ${state.teamRoster?.chung?.length||0}`)}{metric('CURRENT',state.currentRound)}{metric('STATUS',state.status.toUpperCase())}</div></section>}

      {tab==='LIVE STATS'&&<section className="panel p-4"><div className="flex items-center justify-between mb-4"><div><h2 className="font-display font-black text-sm text-[hsl(var(--gold))] text-[hsl(var(--gold))]">LIVE STATISTICS + PERFORMANCE</h2><p className="text-[9px] text-muted-foreground">Current match updates from the scoring engine</p></div><BarChart3 size={18} className="text-[hsl(var(--gold))]"/></div><div className="grid md:grid-cols-2 gap-4">{(['chung','hong'] as const).map(side=><div key={side} className={`rounded-2xl border p-4 ${side==='chung'?'border-blue-500/20':'border-red-500/20'}`}><div className="flex items-center justify-between"><div className="font-black text-lg">{side==='chung'?'BLUE':'RED'} · {state[side].player.name}</div><div className="text-3xl font-display font-black">{stats.score[side]}</div></div><div className="grid grid-cols-3 gap-2 mt-4">{metric('HITS',stats.hits[side])}{metric('HEAD',stats.head[side])}{metric('BODY',stats.body[side])}{metric('ROUNDS',stats.rounds)}{metric('PERFORMANCE',stats.perf(side))}{metric('PENALTIES',stats.warnings)}</div></div>)}</div><div className="mt-4 rounded-xl border border-[hsl(var(--gold))]/20 bg-[hsl(var(--gold))]/5 p-4"><div className="text-[9px] font-black text-[hsl(var(--gold))]">MATCH MVP RECOMMENDATION</div><div className="text-xl font-display font-black mt-1">{stats.perf('chung')>=stats.perf('hong')?state.chung.player.name:state.hong.player.name}</div><div className="text-[10px] text-muted-foreground mt-1">Performance Score {Math.max(stats.perf('chung'),stats.perf('hong'))}/100 · derived from score, hits, rounds and result</div></div></section>}

      {tab==='AWARDS'&&<section className="panel p-4"><div className="flex items-center gap-2 mb-4"><Award className="text-[hsl(var(--gold))]"/><div><h2 className="font-display font-black text-sm">AWARDS & PODIUM</h2><p className="text-[9px] text-muted-foreground">Broadcast-ready award candidates using live tournament data</p></div></div><div className="grid md:grid-cols-3 gap-3">{[['TEAM MATCH MVP',stats.perf('chung')>=stats.perf('hong')?state.chung.player.name:state.hong.player.name],['BEST PLAYER',stats.perf('chung')>=stats.perf('hong')?state.chung.player.name:state.hong.player.name],['FAIR PLAY',stats.warnings===0?(stats.perf('chung')>=stats.perf('hong')?state.chung.player.name:state.hong.player.name):'Review required'],['BEST TEAM',state.result?teamScore[state.result.winner==='chung'?'blue':'red']:'Pending'],['TOURNAMENT MVP',stats.perf('chung')>=stats.perf('hong')?state.chung.player.name:state.hong.player.name],['PODIUM',state.result?'1 · 2 · 3':'Pending']].map(([a,b])=><div key={a} className="rounded-2xl border border-[hsl(var(--gold))]/20 p-5 bg-[hsl(var(--gold))]/5"><div className="text-[9px] text-[hsl(var(--gold))] font-black">{a}</div><div className="text-xl font-display font-black mt-2">{b}</div></div>)}</div></section>}


      {tab==='RANKINGS'&&<section className="panel p-4"><div className="flex items-center justify-between mb-4"><div><h2 className="font-display font-black text-sm text-[hsl(var(--gold))]">TOURNAMENT RANKINGS</h2><p className="text-[9px] text-muted-foreground">Performance Score · Win Rate · Points · Hits · Fair Play</p></div><Trophy className="text-[hsl(var(--gold))]" size={20}/></div><div className="overflow-x-auto"><table className="w-full text-[9px]"><thead><tr className="text-muted-foreground border-b border-white/10"><th className="text-left p-2">#</th><th className="text-left p-2">PLAYER</th><th className="p-2">W/L</th><th className="p-2">POINTS</th><th className="p-2">HITS</th><th className="p-2">FAIR PLAY</th><th className="p-2">PERFORMANCE</th></tr></thead><tbody>{[...tournamentRows].sort((a,b)=>b.performanceScore-a.performanceScore).map((p,i)=><tr key={p.id||p.name} className="border-b border-white/5"><td className="p-2 font-black text-[hsl(var(--gold))]">{i+1}</td><td className="p-2 font-black">{p.name}<div className="text-[8px] text-muted-foreground">{p.team||p.club||'Independent'}</div></td><td className="p-2 text-center">{p.wins}/{p.losses}</td><td className="p-2 text-center">{p.pointsFor}</td><td className="p-2 text-center">{p.hits}</td><td className="p-2 text-center">{Math.round(p.fairPlay)}</td><td className="p-2 text-center font-black">{p.performanceScore.toFixed(2)}</td></tr>)}</tbody></table></div><div className="mt-4 rounded-xl border border-[hsl(var(--gold))]/20 bg-[hsl(var(--gold))]/5 p-4"><div className="text-[9px] font-black text-[hsl(var(--gold))]">MVP ENGINE</div><div className="text-xl font-display font-black">{mvp?.player.name||'—'}</div><div className="text-[9px] text-muted-foreground">AI Score {mvp?.score?.toFixed(2)||'—'} · Confidence {mvp?.confidence||0}% · {mvp?.reason}</div></div></section>}

      {tab==='GRAPHICS'&&<section className="panel p-4"><div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2 rounded-2xl border border-[hsl(var(--gold))]/30 bg-black/30 p-6 relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-br from-blue-500/10 via-transparent to-red-500/10"/><div className="relative"><div className="text-[9px] tracking-[.3em] text-[hsl(var(--gold))] font-black">WAB-TKD · BEST PLAYER</div><div className="mt-6 grid md:grid-cols-[1fr_auto_1fr] items-center gap-5"><div className="text-blue-300"><div className="text-[9px] font-black">BLUE</div><div className="text-2xl font-display font-black">{state.chung.player.name}</div><div className="text-[9px] text-muted-foreground">{state.chung.player.club||'—'} · {state.chung.player.nationality}</div></div><div className="text-5xl font-display font-black text-[hsl(var(--gold))]">MVP</div><div className="text-right text-red-300"><div className="text-[9px] font-black">RED</div><div className="text-2xl font-display font-black">{state.hong.player.name}</div><div className="text-[9px] text-muted-foreground">{state.hong.player.club||'—'} · {state.hong.player.nationality}</div></div></div><div className="mt-7 grid grid-cols-4 gap-2">{metric('SCORE',mvp?.score?.toFixed(2)||'—')}{metric('HITS',mvp?.player.hits||0)}{metric('HEAD',mvp?.player.headHits||0)}{metric('FAIR PLAY',Math.round(mvp?.player.fairPlay||0))}</div></div></div><div className="space-y-3"><div className="rounded-xl border border-white/10 p-4"><div className="text-[9px] font-black text-[hsl(var(--gold))]">BROADCAST OUTPUT</div><div className="text-xs font-black mt-2">MVP · VICTORY · PLAYER STATS · PODIUM</div><div className="text-[9px] text-muted-foreground mt-2">Uses live player data. Public Display remains output-only.</div></div><button onClick={()=>{setBroadcast('MVP');logAudit('broadcast_graphic','MVP graphic selected');toast.success('MVP graphic ready')}} className="w-full rounded-xl bg-[hsl(var(--gold))] text-black py-3 text-[10px] font-black">SEND MVP TO BROADCAST</button></div></div></section>}

      {tab==='USERS'&&<section className="panel p-4"><div className="mb-4"><h2 className="font-display font-black text-sm text-[hsl(var(--gold))]">USERS & ACCESS</h2><p className="text-[9px] text-muted-foreground">Local authenticated accounts · role-based permissions · audit identity</p></div><TournamentUsersPanel/></section>}

      {tab==='HEALTH'&&<section className="panel p-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{metric('DATABASE','ONLINE')}{metric('AUTO SAVE','ACTIVE')}{metric('PUBLIC DISPLAY',mats.length?'CONNECTED':'WAITING')}{metric('LIVE MATS',liveCount)}{metric('QUEUE',queue.length)}{metric('CURRENT MATCH',state.matchNumber??'—')}{metric('MAT',state.matNumber??'—')}{metric('USER',userName||'—')}{metric('SYNC QUEUE',getPendingSyncActions().length)}{metric('NETWORK',isOnline()?'ONLINE':'OFFLINE')}</div><div className="mt-4 space-y-2">{mats.map(m=><div key={m.mat_number} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><div className="font-black text-xs">MAT {String(m.mat_number).padStart(2,'0')}</div><div className="text-[9px]">{m.device_name||'—'} · {m.locked?'LOCKED':m.online===false?'OFFLINE':'ONLINE'}</div></div>)}</div></section>}

      {tab==='EXPORT'&&<section className="panel p-4"><div className="flex items-center gap-2"><Download className="text-[hsl(var(--gold))]"/><div><h2 className="font-display font-black text-sm">TOURNAMENT PACKAGE</h2><p className="text-[9px] text-muted-foreground">Results · players · teams · matches · stats · rankings · MVP · Fair Play · Club Points · Audit · snapshots</p></div></div><div className="grid md:grid-cols-3 gap-3 mt-5">{metric('TOURNAMENTS',localTournaments.length)}{metric('AUDIT ENTRIES',getAuditLog().length)}{metric('CURRENT MATCH',state.matchNumber??'—')}</div><button onClick={exportTournament} className="mt-5 w-full py-3 rounded-xl bg-[hsl(var(--gold))] text-black font-black text-xs flex items-center justify-center gap-2"><Download size={15}/> EXPORT TOURNAMENT PACKAGE</button></section>}

      {tab==='EMERGENCY'&&<section className="panel p-4"><div className="flex items-center gap-2 mb-4"><ShieldAlert className="text-red-300"/><div><h2 className="font-display font-black text-sm">EMERGENCY CONTROL</h2><p className="text-[9px] text-muted-foreground">Supervisor-only safety actions. Results are not deleted.</p></div></div>{!isSupervisor?<div className="rounded-xl border border-red-500/20 p-4 text-red-300 text-xs font-black">SUPERVISOR APPROVAL REQUIRED</div>:<div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3">{[['EMERGENCY PAUSE',emergencyPause,Pause],['RESUME',resume,Zap],['LOCK MATCH',lockMatch,Lock],['RECOVER SAFE SNAPSHOT',()=>{logAudit('recover_request','Safe snapshot recovery requested');toast.info('Recovery request recorded');},RefreshCw],['SWITCH MAT',()=>{logAudit('switch_mat','Central mat switch requested');toast.info('Use Mat Control Center to complete switch');},Monitor],['REPLACE DISPLAY',()=>{logAudit('replace_display','Public display replacement requested');toast.info('Open Tournament Wall on replacement display');},Monitor]].map(([label,fn,Icon]:any)=><button key={label as string} onClick={fn as any} className="rounded-xl border border-white/10 p-4 text-left bg-white/[0.03] hover:border-red-400/40"><Icon size={17} className="text-red-300"/><div className="font-black text-xs mt-3">{label}</div><div className="text-[8px] text-muted-foreground mt-1">Logged to Audit</div></button>)}</div>}{emergency&&<div className="mt-4 rounded-xl border border-red-500/40 bg-red-500/10 p-3 text-red-200 text-xs font-black">EMERGENCY STATE ACTIVE · CURRENT MATCH PAUSED</div>}</section>}

      <footer className="text-[8px] text-muted-foreground flex items-center gap-3 px-1"><ShieldCheck size={10}/> {userName||'Not signed in'} · {role} · <span>Last snapshot: live session state</span></footer>
    </div>
  </div>
}
