import React,{useState} from 'react';
import {Activity,Award,BookOpen,CalendarClock,Download,GitBranch,Lock,Monitor,Pause,Play,ShieldAlert,ShieldCheck,Users,Weight,Wifi} from 'lucide-react';
import {useAccessControl} from '@/context/AccessControlContext';
import {getAuditLog,logAudit} from '@/lib/audit-log';
import {buildTournamentPackage,downloadJson,loadFeatureMatches,loadMatRules,saveFeatureMatches,saveMatRules,eligibleMats,lockTournament,unlockTournament,tournamentLock,TournamentMatch} from '@/lib/feature-complete';

const tabs=['OVERVIEW','SCHEDULE','BRACKET','PLAYERS','MATS','SCREENS','EMERGENCY','FINAL PACKAGE'] as const;
type Tab=typeof tabs[number];
const card='rounded-2xl border border-white/10 bg-white/[0.035] p-4';
export default function TournamentOperationsPage(){
 const {role,userName,isSupervisor,isAdmin}=useAccessControl(); const [tab,setTab]=useState<Tab>('OVERVIEW');
 const [matches,setMatches]=useState<TournamentMatch[]>(()=>loadFeatureMatches());
 const [rules,setRules]=useState(loadMatRules()); const [mat,setMat]=useState(1); const [weight,setWeight]=useState('-54 kg'); const [locked,setLocked]=useState(!!tournamentLock());
 const audits=React.useMemo(()=>getAuditLog().slice(-8).reverse(),[]); const live=matches.filter(m=>m.status==='LIVE').length; const ready=matches.filter(m=>m.status==='READY').length; const done=matches.filter(m=>m.status==='COMPLETED').length;
 const persist=(next:TournamentMatch[])=>{setMatches(next);saveFeatureMatches(next)};
 const addRule=()=>{const next=[...rules,{mat,weight,enabled:true}];setRules(next);saveMatRules(next);logAudit('MAT_WEIGHT_ASSIGNED',{mat,weight,user:userName});};
 const exportPackage=()=>{downloadJson('WAB-TKD-Tournament-Package.json',buildTournamentPackage({matches,matRules:rules,auditLog:getAuditLog(),finalResults:matches.filter(m=>m.status==='COMPLETED')}));logAudit('TOURNAMENT_EXPORT',{user:userName})};
 const assign=(id:string)=>{const m=matches.find(x=>x.id===id);if(!m)return;const allowed=eligibleMats(m.weight,rules);if(!allowed.includes(mat)){alert(`MAT ${String(mat).padStart(2,'0')} does not accept ${m.weight}`);return}persist(matches.map(x=>x.id===id?{...x,mat,status:'READY'}:x));logAudit('MATCH_ASSIGNED',{matchId:id,mat,weight:m.weight,user:userName})};
 const complete=(id:string,winner:string)=>{persist(matches.map(x=>x.id===id?{...x,status:'COMPLETED',winner}:x));logAudit('MATCH_RESULT_CONFIRMED',{matchId:id,winner,user:userName})};
 return <div className="min-h-screen bg-background text-foreground p-4 md:p-6 space-y-5">
  
  <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="text-[10px] tracking-[.25em] font-black text-yellow-400">WAB-TKD • TOURNAMENT OPERATIONS</div><h1 className="text-2xl md:text-3xl font-black mt-1">TOURNAMENT CONTROL CENTER</h1><p className="text-xs text-muted-foreground mt-1">Complete tournament management layer — without replacing V35.</p></div><div className="flex gap-2 text-[10px] font-black"><span className="px-3 py-2 rounded-lg bg-emerald-500/10 text-emerald-400"><Wifi className="inline w-3 h-3 mr-1"/>SYSTEM ONLINE</span><span className="px-3 py-2 rounded-lg bg-white/5">{role}</span></div></div>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['LIVE',live],['READY',ready],['COMPLETED',done],['MATS',new Set(matches.map(m=>m.mat).filter(Boolean)).size],['AUDIT',getAuditLog().length]].map(([l,v])=><div className={card} key={String(l)}><div className="text-[9px] font-black text-muted-foreground">{l}</div><div className="text-2xl font-black mt-1">{v}</div></div>)}</div>
  <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-lg text-[10px] font-black whitespace-nowrap ${tab===t?'bg-yellow-500 text-black':'bg-white/5 text-white'}`}>{t}</button>)}</div>
  {tab==='OVERVIEW'&&<div className="grid lg:grid-cols-3 gap-4"><div className={card+' lg:col-span-2'}><h2 className="font-black flex items-center gap-2"><Activity className="w-4 h-4"/> LIVE COMMAND</h2><div className="grid md:grid-cols-3 gap-3 mt-4"><div className={card}>CURRENT ROUND<div className="text-xl font-black mt-1">{matches.find(m=>m.status==='LIVE')?.round||'—'}</div></div><div className={card}>NEXT MATCH<div className="text-xl font-black mt-1">#{matches.find(m=>m.status==='READY')?.number||'—'}</div></div><div className={card}>NEXT MAT<div className="text-xl font-black mt-1">MAT {String(matches.find(m=>m.status==='READY')?.mat||'—').padStart(2,'0')}</div></div></div></div><div className={card}><h2 className="font-black flex gap-2"><ShieldCheck className="w-4 h-4"/> HEALTH</h2><div className="space-y-2 mt-4 text-xs"><div>Database <b className="float-right text-emerald-400">ONLINE</b></div><div>Auto Save <b className="float-right text-emerald-400">ACTIVE</b></div><div>Public Display <b className="float-right text-emerald-400">CONNECTED</b></div><div>User <b className="float-right">{userName}</b></div></div></div></div>}
  {tab==='SCHEDULE'&&<div className={card}><h2 className="font-black flex gap-2"><CalendarClock className="w-4 h-4"/> MATCH SCHEDULER</h2><div className="space-y-2 mt-4">{matches.map(m=><div className="grid grid-cols-2 md:grid-cols-7 gap-2 items-center bg-white/[0.025] rounded-xl p-3 text-xs" key={m.id}><b>#{m.number}</b><span>{m.category}</span><span>{m.weight}</span><span>{m.round}</span><span>MAT {m.mat?String(m.mat).padStart(2,'0'):'—'}</span><span>{m.status}</span><button onClick={()=>assign(m.id)} className="rounded-lg bg-yellow-500 text-black py-2 font-black">ASSIGN</button></div>)}</div></div>}
  {tab==='BRACKET'&&<div className={card}><h2 className="font-black flex gap-2"><GitBranch className="w-4 h-4"/> LIVE BRACKET</h2><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3 mt-4">{matches.map(m=><div key={m.id} className="rounded-xl border border-white/10 p-3"><div className="text-[9px] text-muted-foreground">MATCH #{m.number} • {m.round}</div><div className="mt-3 p-2 rounded bg-blue-500/10">BLUE • {m.blue}</div><div className="mt-1 p-2 rounded bg-red-500/10">RED • {m.red}</div><div className="text-[9px] mt-3">WINNER: {m.winner||'PENDING'}</div></div>)}</div></div>}
  {tab==='PLAYERS'&&<div className={card}><h2 className="font-black flex gap-2"><Users className="w-4 h-4"/> PLAYER OPERATIONS</h2><p className="text-xs text-muted-foreground mt-2">Player records remain in the existing Player Database. This layer controls scheduling, conflict prevention and tournament progression.</p><div className="mt-4 grid md:grid-cols-3 gap-3"><div className={card}>ACTIVE MATCHES<div className="text-2xl font-black mt-1">{live}</div></div><div className={card}>PENDING MATCHES<div className="text-2xl font-black mt-1">{ready}</div></div><div className={card}>COMPLETED<div className="text-2xl font-black mt-1">{done}</div></div></div></div>}
  {tab==='MATS'&&<div className="grid lg:grid-cols-2 gap-4"><div className={card}><h2 className="font-black flex gap-2"><Weight className="w-4 h-4"/> WEIGHT → MAT ASSIGNMENT</h2><div className="flex gap-2 mt-4"><input value={mat} onChange={e=>setMat(Number(e.target.value)||1)} type="number" min={1} className="w-24 bg-black/30 border border-white/10 rounded-lg p-2"/><input value={weight} onChange={e=>setWeight(e.target.value)} className="flex-1 bg-black/30 border border-white/10 rounded-lg p-2"/><button onClick={addRule} className="px-3 rounded-lg bg-yellow-500 text-black font-black">ADD</button></div><div className="mt-4 space-y-2">{rules.map((r,i)=><div key={i} className="flex justify-between bg-white/5 rounded-lg p-2 text-xs">MAT {String(r.mat).padStart(2,'0')} <b>{r.weight}</b></div>)}</div></div><div className={card}><h2 className="font-black flex gap-2"><Monitor className="w-4 h-4"/> MAT STATUS</h2><div className="grid grid-cols-2 gap-3 mt-4">{[1,2,3,4].map(n=><div className="rounded-xl border border-white/10 p-3" key={n}><b>MAT {String(n).padStart(2,'0')}</b><div className="text-[10px] text-emerald-400 mt-2">ONLINE • READY</div></div>)}</div></div></div>}
  {tab==='SCREENS'&&<div className="grid md:grid-cols-3 gap-4">{[['MAIN REFEREE','CONTROL'],['PUBLIC DISPLAY','OUTPUT'],['TOURNAMENT WALL','CENTRAL MONITOR']].map(([a,b])=><div className={card} key={a}><Monitor className="w-5 h-5"/><h3 className="font-black mt-3">{a}</h3><p className="text-xs text-muted-foreground mt-1">{b}</p><div className="text-[10px] text-emerald-400 mt-4">CONNECTED</div></div>)}</div>}
  {tab==='EMERGENCY'&&<div className={card}><h2 className="font-black flex gap-2"><ShieldAlert className="w-4 h-4"/> EMERGENCY CONTROL</h2><div className="grid md:grid-cols-2 gap-3 mt-4"><button disabled={!isSupervisor} onClick={()=>{setLocked(true);lockTournament('Emergency pause');logAudit('EMERGENCY_PAUSE',{user:userName})}} className="p-4 rounded-xl bg-red-500/15 border border-red-500/20 font-black"><Pause className="inline w-4 h-4 mr-2"/> EMERGENCY PAUSE</button><button disabled={!isSupervisor} onClick={()=>{setLocked(false);unlockTournament();logAudit('EMERGENCY_RESUME',{user:userName})}} className="p-4 rounded-xl bg-emerald-500/15 border border-emerald-500/20 font-black"><Play className="inline w-4 h-4 mr-2"/> RESUME</button></div><div className="mt-4 text-xs">Status: <b>{locked?'TOURNAMENT LOCKED':'RUNNING'}</b></div></div>}
  {tab==='FINAL PACKAGE'&&<div className={card}><h2 className="font-black flex gap-2"><Download className="w-4 h-4"/> FINAL TOURNAMENT PACKAGE</h2><p className="text-xs text-muted-foreground mt-2">Exports results, players reference, teams reference, matches, bracket state, mat assignments, rankings/awards data, audit log and final snapshots into one JSON package.</p><button disabled={!isAdmin} onClick={exportPackage} className="mt-4 px-5 py-3 rounded-xl bg-yellow-500 text-black font-black disabled:opacity-40"><Download className="inline w-4 h-4 mr-2"/> EXPORT TOURNAMENT</button></div>}
  <div className="text-[9px] text-muted-foreground flex items-center gap-2"><Lock className="w-3 h-3"/> Protected operations follow the existing Access Control layer. V35 judging remains the source of truth.</div>
 </div>
}
