import React, {useState } from 'react';
import { Archive, Award, BarChart3, CheckCircle2, Download, FileText, Flag, Lock, Palette, Settings2, ShieldCheck, Trophy, Users, Weight } from 'lucide-react';
import { useAccessControl } from '@/context/AccessControlContext';
import { getAuditLog, logAudit } from '@/lib/audit-log';
import { downloadJson, buildTournamentPackage, loadFeatureMatches, loadMatRules } from '@/lib/feature-complete';
import { buildFinalReport, downloadReport, downloadReportXlsx, printReport, FinalReportKind } from '@/lib/final-reports';
import { getTournamentPerformanceRows } from '@/lib/tournament-intelligence';

type Tab = 'DESIGN'|'AWARDS'|'REPORTS'|'ARCHIVE'|'SETTINGS'|'SECURITY';
const tabs:Tab[]=['DESIGN','AWARDS','REPORTS','ARCHIVE','SETTINGS','SECURITY'];
const card='rounded-2xl border border-white/10 bg-white/[0.035] p-4';
const KEY='wab-tkd-finalization-v1';
function load(){ try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}} }
export default function TournamentFinalizationPage(){
 const {role,userName,isSupervisor,isAdmin}=useAccessControl(); const [tab,setTab]=useState<Tab>('DESIGN'); const [state,setState]=useState<any>(load());
 const matches=React.useMemo(()=>loadFeatureMatches(),[]); const rules=React.useMemo(()=>loadMatRules(),[]); const audits=getAuditLog();
 const finalReport=React.useMemo(()=>buildFinalReport('FINAL_RESULTS', matches as any),[matches]);
 const awards=React.useMemo(()=>finalReport.awards,[finalReport]);
 const performance=React.useMemo(()=>getTournamentPerformanceRows(),[matches,state]);
 const save=(patch:any)=>{const next={...state,...patch};setState(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const exportAll=()=>{downloadJson('WAB-TKD-FINAL-TOURNAMENT-PACKAGE.json',buildTournamentPackage({matches,matRules:rules,auditLog:audits,finalResults:matches.filter((m:any)=>m.status==='COMPLETED')}));logAudit('FINAL_PACKAGE_EXPORT',{user:userName});};
 const finalize=()=>{if(!isSupervisor)return;save({finalized:true,finalizedAt:new Date().toISOString(),finalizedBy:userName});logAudit('TOURNAMENT_FINALIZED',{user:userName});};
 return <div className="min-h-screen bg-background text-foreground p-4 md:p-6 space-y-5">
  
  <header className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="text-[10px] tracking-[.28em] font-black text-yellow-400">WAB-TKD • FINAL TOURNAMENT LAYER</div><h1 className="text-3xl font-black mt-1">TOURNAMENT FINISH & ARCHIVE</h1><p className="text-xs text-muted-foreground mt-1">Awards, reports, archive, configuration and final broadcast identity — layered over the existing V35 engine.</p></div><div className="flex gap-2"><span className="px-3 py-2 rounded-lg bg-white/5 text-[10px] font-black">{role}</span><span className="px-3 py-2 rounded-lg bg-emerald-500/10 text-emerald-400 text-[10px] font-black"><ShieldCheck className="inline w-3 h-3 mr-1"/>PROTECTED</span></div></header>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['MATCHES',matches.length],['COMPLETED',matches.filter((m:any)=>m.status==='COMPLETED').length],['WEIGHT RULES',rules.length],['AUDIT',audits.length],['STATUS',state.finalized?'FINAL':'OPEN']].map(([a,b])=><div className={card} key={String(a)}><div className="text-[9px] text-muted-foreground font-black">{a}</div><div className="text-xl font-black mt-1">{b}</div></div>)}</div>
  <nav className="flex gap-2 overflow-x-auto">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-2 rounded-lg text-[10px] font-black ${tab===t?'bg-yellow-500 text-black':'bg-white/5'}`}>{t}</button>)}</nav>
  {tab==='DESIGN'&&<section className={card}><div className="flex items-center gap-2"><Palette className="text-yellow-400"/><div><h2 className="font-black">WAB-TKD BROADCAST IDENTITY</h2><p className="text-[10px] text-muted-foreground">One visual language for all final screens. Existing player assets remain data-driven.</p></div></div><div className="grid md:grid-cols-4 gap-3 mt-5">{[['PLAYER CALL','BLUE / RED / GOLD'],['MVP','GOLD / BLACK / ENERGY'],['VICTORY','GOLD / RED / BLUE'],['PODIUM','CHAMPIONSHIP GOLD']].map(([a,b])=><div className="rounded-xl border border-yellow-500/20 p-4 bg-gradient-to-br from-yellow-500/10 via-black/20 to-blue-500/10" key={a}><div className="text-[9px] text-yellow-400 font-black">{a}</div><div className="text-xs font-black mt-2">{b}</div><div className="text-[8px] text-muted-foreground mt-2">LIVE DATA • NO HARDCODED PLAYER TEXT</div></div>)}</div><div className="mt-5 grid md:grid-cols-3 gap-3">{['NEXT MATCH','LIVE MATCH','BEST PLAYER'].map(x=><button key={x} onClick={()=>logAudit('broadcast_template_selected',{template:x,user:userName})} className="rounded-xl border border-white/10 p-4 text-left hover:border-yellow-400/40"><Trophy size={16} className="text-yellow-400"/><div className="font-black text-xs mt-3">{x}</div><div className="text-[8px] text-muted-foreground mt-1">Broadcast template ready</div></button>)}</div></section>}
  {tab==='AWARDS'&&<section className={card}><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Award className="text-yellow-400"/><h2 className="font-black">FINAL AWARDS</h2></div><button onClick={()=>printReport('AWARDS_REPORT',matches as any)} className="px-3 py-2 rounded-lg bg-white/10 text-[10px] font-black">PRINT AWARDS</button></div><div className="grid md:grid-cols-3 gap-3 mt-5">{awards.map((a:any)=><div className="rounded-xl border border-yellow-500/15 bg-yellow-500/5 p-4" key={a.key}><div className="text-[9px] text-yellow-400 font-black">{a.title}</div><div className="text-sm font-black mt-2">{a.winner}</div><div className="text-[8px] text-muted-foreground mt-1">{a.reason}</div><div className="text-[9px] font-black mt-2">SCORE {a.score}</div></div>)}{performance.length===0&&<div className="md:col-span-3 text-xs text-muted-foreground">No player performance ledger is available yet. Awards remain empty rather than inventing winners.</div>}</div></section>}
  {tab==='REPORTS'&&<section className={card}><div className="flex items-center gap-2"><FileText className="text-yellow-400"/><h2 className="font-black">TOURNAMENT REPORTS</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3 mt-5">{(['FINAL_RESULTS','BRACKET_REPORT','PLAYER_REPORT','TEAM_REPORT','CLUB_REPORT','RANKING_REPORT','FAIR_PLAY_REPORT','MATCH_REPORT','AWARDS_REPORT'] as FinalReportKind[]).map(r=><div key={r} className="rounded-xl border border-white/10 p-4 hover:border-yellow-400/30"><BarChart3 size={16} className="text-yellow-400"/><div className="font-black text-xs mt-3">{r.replaceAll('_',' ')}</div><div className="text-[8px] text-muted-foreground mt-1">Built from saved tournament data</div><div className="flex gap-2 mt-3"><button onClick={()=>{downloadReport(r,matches as any);logAudit('report_exported',{report:r,user:userName})}} className="px-3 py-2 rounded-lg bg-white/10 text-[9px] font-black">CSV</button><button onClick={()=>{downloadReportXlsx(r,matches as any);logAudit('report_exported_xlsx',{report:r,user:userName})}} className="px-3 py-2 rounded-lg bg-emerald-600/80 text-white text-[9px] font-black">XLSX</button><button onClick={()=>{printReport(r,matches as any);logAudit('report_printed',{report:r,user:userName})}} className="px-3 py-2 rounded-lg bg-yellow-500 text-black text-[9px] font-black">PRINT</button></div></div>)}</div><button onClick={exportAll} className="mt-5 w-full rounded-xl bg-yellow-500 text-black py-3 font-black text-xs"><Download className="inline w-4 h-4 mr-2"/>EXPORT COMPLETE TOURNAMENT PACKAGE</button></section>}
  {tab==='ARCHIVE'&&<section className={card}><div className="flex items-center gap-2"><Archive className="text-yellow-400"/><h2 className="font-black">TOURNAMENT ARCHIVE</h2></div><div className="mt-5 rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between"><div><div className="font-black">CURRENT TOURNAMENT</div><div className="text-[9px] text-muted-foreground mt-1">{state.finalized?'FINALIZED':'OPEN FOR OPERATIONS'}</div></div><span className={`text-[10px] font-black ${state.finalized?'text-emerald-400':'text-yellow-400'}`}>{state.finalized?'ARCHIVED READY':'ACTIVE'}</span></div>{state.finalized&&<div className="text-[9px] mt-4 text-muted-foreground">Finalized by {state.finalizedBy} · {state.finalizedAt}</div>}</div><button disabled={!isSupervisor||state.finalized} onClick={finalize} className="mt-4 rounded-xl bg-yellow-500 text-black px-5 py-3 font-black text-xs disabled:opacity-40"><Lock className="inline w-4 h-4 mr-2"/>FINALIZE & LOCK RESULTS</button></section>}
  {tab==='SETTINGS'&&<section className={card}><div className="flex items-center gap-2"><Settings2 className="text-yellow-400"/><h2 className="font-black">ADVANCED TOURNAMENT SETTINGS</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3 mt-5">{[['MATS','4'],['WEIGHT RULES',String(rules.length)],['BRACKET','KNOCKOUT'],['SEEDING','ENABLED'],['BYE','AUTO'],['CONSOLATION','CONFIGURABLE'],['ROUND DURATION','CONFIGURABLE'],['REST RULE','CONFIGURABLE']].map(([a,b])=><div className="rounded-xl border border-white/10 p-4" key={a}><Weight size={15} className="text-yellow-400"/><div className="text-[9px] font-black mt-3">{a}</div><div className="text-xs font-black mt-1">{b}</div></div>)}</div><p className="text-[9px] text-muted-foreground mt-5">These controls are intentionally separated from V35 scoring rules. Tournament configuration may be expanded without replacing the existing judging engine.</p></section>}
  {tab==='SECURITY'&&<section className={card}><div className="flex items-center gap-2"><Users className="text-yellow-400"/><h2 className="font-black">FINAL SECURITY & APPROVAL</h2></div><div className="grid md:grid-cols-3 gap-3 mt-5">{([['RESULT OVERRIDE',isAdmin],['FINALIZE',isSupervisor],['EXPORT',true]] as [string, boolean][]).map(([a,ok])=><div className="rounded-xl border border-white/10 p-4" key={a}><CheckCircle2 className={ok?'text-emerald-400':'text-red-400'} size={16}/><div className="font-black text-xs mt-3">{a}</div><div className="text-[9px] mt-1">{ok?'AUTHORIZED':'SUPERVISOR / ADMIN REQUIRED'}</div></div>)}</div><div className="mt-5 rounded-xl border border-white/10 p-4"><div className="text-[9px] text-yellow-400 font-black">AUDIT TRAIL</div><div className="text-xs font-black mt-2">{audits.slice(-5).reverse().map((a:any,i)=><div key={i} className="py-2 border-b border-white/5">{a.action||a.event||'EVENT'} · {a.user||a.actor||userName||'SYSTEM'}</div>)}</div></div></section>}
 </div>
}
