import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Archive, BarChart3, CheckCircle2, Clock3, ExternalLink, FileText, Lock, MapPin, Monitor, Play, Radio, RefreshCw, Trophy, Users, Video, WifiOff, Zap } from 'lucide-react';
import { useI18n } from '@/lib/i18n';
import { useAccessControl } from '@/context/AccessControlContext';
import { loadAllLocalTournaments } from '@/lib/tournament-local';
import { supabase, isSupabaseConfigured } from '@/integrations/supabase/client';
import { fetchAllMatStatuses, getMatCount, MatLiveStatus } from '@/lib/mat-status';
import { getCountryFlag } from '@/lib/flags';
import { getSavedMatchesForTournament, getTournamentMatchSummary, SavedMatchRecord } from '@/lib/match-records';
import { getMatCategoryPlan } from '@/lib/mat-category-plan';
import type { Player } from '@/types/tkd';

interface SavedTournament { id:string; name:string; gender:string; weight_category:string; age_group:string; format:string; status?:string; bracket_data?:any; players?:Player[]; created_at?:string; updated_at?:string; }
interface MatchRow { id:string; matchNumber:number; stage:string; round:number; p1?:Player; p2?:Player; winner?:string; score?:string; status:'COMPLETED'|'LIVE'|'READY'|'WAITING'|'LOCKED'; record?:SavedMatchRecord|null; replay:boolean; }
const FALLBACK_NAME = (side:'blue'|'red') => side==='blue'?'CHUNG':'HONG';
const stageRank = (s:string) => { const x=String(s||'').toUpperCase(); if(x.includes('FINAL')&&!x.includes('SEMI')) return 5; if(x.includes('SEMI')) return 4; if(x.includes('QUARTER')) return 3; if(x.includes('16')) return 2; return 1; };
const stageLabel = (s:string, r:number) => { const x=String(s||'').toUpperCase(); if(x) return x.replace('QUARTERFINAL','QUARTER-FINAL').replace('SEMIFINAL','SEMI-FINAL'); if(r>0) return `ROUND ${r}`; return 'QUALIFICATION'; };

function StatusPill({status}:{status:string}) { const cls = status==='COMPLETED'?'archive-status-done':status==='LIVE'?'archive-status-live':status==='READY'?'archive-status-ready':status==='LOCKED'?'archive-status-locked':'archive-status-waiting'; return <span className={`archive-status ${cls}`}>{status}</span>; }
function MiniPlayer({p,side}:{p?:Player;side:'blue'|'red'}) { const name=p?.name?.trim()||FALLBACK_NAME(side); return <div className={`archive-player archive-player-${side}`}><div className="archive-avatar">{p?.photo||p?.photoUrl?<img src={p.photo||p.photoUrl} alt=""/>:<span>{name.slice(0,1)}</span>}</div><div className="min-w-0"><div className="archive-player-name">{name}</div><div className="archive-player-meta">{p?.nationality?getCountryFlag(p.nationality)+' ':''}{p?.club||'—'}{p?.playerNumber!=null?` · #${p.playerNumber}`:''}</div></div></div>; }

export default function TournamentControlCenter(){
 const {lang}=useI18n(); const {role}=useAccessControl(); const ar=lang==='ar';
 const [tournaments,setTournaments]=useState<SavedTournament[]>([]); const [selectedId,setSelectedId]=useState(''); const [mats,setMats]=useState<MatLiveStatus[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [tab,setTab]=useState<'OVERVIEW'|'MATCHES'|'BRACKET'|'PLAYERS'>('OVERVIEW');
 const load=useCallback(async()=>{setRefreshing(true); try{const locals=loadAllLocalTournaments() as SavedTournament[]; let cloud:any[]=[]; if(isSupabaseConfigured){try{const {data}=await (supabase as any).from('tournaments').select('*').order('created_at',{ascending:false}); cloud=data||[];}catch{}} const merged=[...cloud,...locals.filter(l=>!cloud.some(c=>c.id===l.id))]; setTournaments(merged); setSelectedId(id=>id||merged[0]?.id||''); setMats(await fetchAllMatStatuses());}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{void load(); const i=window.setInterval(()=>void load(),4000); return()=>window.clearInterval(i)},[load]);
 const tournament=tournaments.find(t=>t.id===selectedId);
 const summary=useMemo(()=>getTournamentMatchSummary(tournament),[tournament]);
 const records=useMemo(()=>tournament?getSavedMatchesForTournament(tournament.id,tournament.name,tournament):[],[tournament]);
 const recordById=useMemo(()=>new Map(records.map(r=>[String(r.match_id||r.id),r])),[records]);
 const scheduled=useMemo(()=>{if(!tournament)return[]; const bd=tournament.bracket_data||{}; const arr=bd.mode==='league'?(bd.league||[]):(bd.bracket||[]); return arr.filter((m:any)=>m&&!m.isBye&&((m.player1&&m.player2)||m.winner));},[tournament]);
 const rows=useMemo<MatchRow[]>(()=>scheduled.map((m:any,i:number)=>{const id=String(m.id);const rec=recordById.get(id);const done=!!rec||!!m.winner;const live=String(m.status||'').toLowerCase();return {id,matchNumber:m.position!=null?m.position+1:m.matchNumber??i+1,stage:stageLabel(m.stage,m.round),round:m.round??1,p1:m.player1,p2:m.player2,winner:rec?.winner||m.winner,score:rec?`${rec.chung_score??0} — ${rec.hong_score??0}`:m.score,status:done?'COMPLETED':(['live','fighting','rest','paused'].includes(live)?'LIVE':m.player1&&m.player2?'READY':'WAITING'),record:rec,replay:Array.isArray(rec?.score_events)&&rec!.score_events.length>0};}),[scheduled,recordById]);
 const allStages=useMemo(()=>Array.from(new Set(rows.map(r=>r.stage))).sort((a,b)=>stageRank(a)-stageRank(b)),[rows]);
 const clubs=useMemo(()=>{const s=new Set<string>();for(const p of (tournament?.players||[]))if(p?.club)s.add(p.club.trim());for(const r of records)for(const c of [r.chung_club,r.hong_club])if(c)s.add(String(c).trim());return [...s].sort();},[tournament,records]);
 const players=useMemo(()=>{const map=new Map<string,Player>();for(const p of (tournament?.players||[]))if(p?.name)map.set(String(p.id||p.name),p);for(const r of records){for(const p of [{id:r.player_ids?.chung,name:r.chung_name,club:r.chung_club,nationality:r.chung_nationality},{id:r.player_ids?.hong,name:r.hong_name,club:r.hong_club,nationality:r.hong_nationality}])if(p.name&&!map.has(String(p.id||p.name)))map.set(String(p.id||p.name),p as Player);}return [...map.values()];},[tournament,records]);
 const liveMats=mats.filter(m=>['running','waiting','paused'].includes(m.status));
 const progress=summary.total?Math.round(summary.completed/summary.total*100):0;
 const openOperator=(r?:MatchRow)=>{if(!r)return; window.location.href='/operator';};
 if(loading&&!tournaments.length)return <div className="min-h-screen bg-black text-white p-8 flex items-center justify-center"><div className="archive-loading"><RefreshCw className="animate-spin"/> LOADING TOURNAMENT CONTROL CENTER</div></div>;
 return <main className="min-h-screen bg-[#050609] text-white p-3 md:p-6" dir={ar?'rtl':'ltr'}>
  <div className="archive-shell">
   <header className="archive-hero"><div><div className="archive-kicker">WAB-TKD · TOURNAMENT CONTROL CENTER PRO</div><h1>TOURNAMENT OPERATIONS & ARCHIVE</h1><p>{ar?'مركز واحد لمعرفة حالة كل فئة ووزن ومباراة وحفظ النتائج والإعادات.':'One control layer for tournament status, weights, matches, results and replay history.'}</p></div><div className="archive-actions"><button className="archive-btn archive-btn-gold" onClick={()=>void load()}><RefreshCw size={15} className={refreshing?'animate-spin':''}/> REFRESH</button><button className="archive-btn" onClick={()=>window.location.href='/operator'}><ExternalLink size={15}/> OPERATOR</button></div></header>
   <section className="archive-toolbar"><select value={selectedId} onChange={e=>setSelectedId(e.target.value)}>{tournaments.map(t=><option key={t.id} value={t.id}>{t.name} · {t.gender} · {t.age_group} · {t.weight_category}</option>)}</select><div className="archive-path"><Archive size={14}/> {tournament?.gender||'—'} / {tournament?.age_group||'—'} / <strong>{tournament?.weight_category||'—'}</strong></div></section>
   {!tournament?<div className="archive-empty"><Archive size={48}/><h2>NO SAVED TOURNAMENT</h2><p>Create or save a tournament first.</p></div>:<>
   <section className="archive-category-card"><div className="archive-category-main"><div className="archive-category-label">CATEGORY</div><div className="archive-category-title">{tournament.age_group} · {tournament.gender} · <strong>{tournament.weight_category}</strong></div><div className="archive-category-sub">{tournament.name} · {tournament.format||'KNOCKOUT'}</div></div><div className="archive-category-status"><StatusPill status={summary.status}/><div className="archive-stage">{summary.currentStage}</div></div></section>
   <section className="archive-metrics">{[['PLAYERS',summary.players,Users],['CLUBS',summary.clubCount,Trophy],['MATCHES',summary.total,ListOrderedIcon],['COMPLETED',summary.completed,CheckCircle2],['REMAINING',summary.remaining,Clock3],['PROGRESS',`${progress}%`,BarChart3]].map(([label,val,Icon]:any)=><div className="archive-metric" key={String(label)}><Icon size={16}/><span>{label}</span><strong>{val}</strong></div>)}</section>
   <nav className="archive-tabs">{(['OVERVIEW','MATCHES','BRACKET','PLAYERS'] as const).map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav>
   {tab==='OVERVIEW'&&<>
    <section className="archive-grid-2"><div className="archive-panel"><div className="archive-panel-title"><BarChart3/> CATEGORY PROGRESS</div><div className="archive-progress"><div style={{width:`${progress}%`}}/></div><div className="archive-progress-labels"><span>{summary.completed} COMPLETED</span><strong>{progress}%</strong><span>{summary.remaining} REMAINING</span></div><div className="archive-stage-grid">{allStages.map(stage=>{const rs=rows.filter(r=>r.stage===stage);const done=rs.filter(r=>r.status==='COMPLETED').length;const pct=rs.length?Math.round(done/rs.length*100):0;const final=stage.includes('FINAL')&&!stage.includes('SEMI');const semi=stage.includes('SEMI');return <div className={`archive-stage-card ${final?'is-final':semi?'is-semi':''}`} key={stage}><span>{stage}</span><strong>{done}/{rs.length}</strong><small>{pct}%</small></div>})}</div></div>
      <div className="archive-panel"><div className="archive-panel-title"><Radio/> MAT LIVE MONITOR</div>{liveMats.length?<div className="archive-live-list">{liveMats.map(m=><div className="archive-live" key={m.mat_number}><div className="archive-live-head"><strong>MAT {String(m.mat_number).padStart(2,'0')}</strong><StatusPill status={m.status==='running'?'LIVE':String(m.status).toUpperCase()}/></div><MiniPlayer p={m.chung_name?{id:'c',name:m.chung_name,club:m.chung_club,nationality:m.chung_nationality}:undefined} side="blue"/><MiniPlayer p={m.hong_name?{id:'h',name:m.hong_name,club:m.hong_club,nationality:m.hong_nationality}:undefined} side="red"/></div>)}</div>:<div className="archive-no-live"><Monitor size={30}/><span>NO ACTIVE MAT</span></div>}</div></section>
    <section className="archive-panel"><div className="archive-panel-title"><Archive/> ARCHIVE HEALTH</div><div className="archive-health-grid"><Health label="ROSTER SNAPSHOT" ok={players.length===summary.players&&players.length>0} value={`${players.length} PLAYERS`}/><Health label="CLUB REGISTRY" ok={clubs.length===summary.clubCount&&clubs.length>0} value={`${clubs.length} CLUBS`}/><Health label="MATCH RECORDS" ok={records.length===summary.completed} value={`${records.length} SAVED`}/><Health label="POINT REPLAY" ok={records.some(r=>Array.isArray(r.score_events)&&r.score_events.length>0)} value={`${records.filter(r=>r.score_events?.length).length} AVAILABLE`}/></div></section>
   </>}
   {tab==='MATCHES'&&<section className="archive-panel"><div className="archive-panel-title"><ListOrderedIcon/> MATCH HISTORY · {rows.length}</div><div className="archive-match-list">{rows.length?rows.map(r=><article className={`archive-match ${r.status==='COMPLETED'?'done':''} ${r.stage.includes('FINAL')&&!r.stage.includes('SEMI')?'final':''} ${r.stage.includes('SEMI')?'semi':''}`} key={r.id}><div className="archive-match-head"><span>MATCH #{String(r.matchNumber).padStart(3,'0')}</span><b>{r.stage}</b><StatusPill status={r.status}/></div><div className="archive-match-players"><MiniPlayer p={r.p1} side="blue"/><div className="archive-score">{r.score||'VS'}<small>{r.winner?`WINNER: ${r.winner==='chung'?(r.p1?.name||FALLBACK_NAME('blue')):(r.p2?.name||FALLBACK_NAME('red'))}`:''}</small></div><MiniPlayer p={r.p2} side="red"/></div><div className="archive-match-foot"><span>{r.record?.win_method||'—'} · {r.record?.duration_seconds?`${Math.round(r.record.duration_seconds)}s`:''}</span><span>{r.replay?<Video size={13}/> : null}{r.replay?' POINT REPLAY AVAILABLE':' NO REPLAY EVENTS'}</span>{r.status==='READY'&&<button className="archive-small-btn" onClick={()=>openOperator(r)}><Play size={12}/> START</button>}{r.status==='COMPLETED'&&<button className="archive-small-btn" onClick={()=>window.location.href='/tournament-dashboard'}><Archive size={12}/> DETAILS</button>}</div></article>):<div className="archive-empty-small">No matches saved in this category.</div>}</div></section>}
   {tab==='BRACKET'&&<section className="archive-panel"><div className="archive-panel-title"><ListOrderedIcon/> BRACKET ROADMAP</div><div className="archive-bracket">{allStages.map(stage=><div className={`archive-bracket-stage ${stage.includes('FINAL')&&!stage.includes('SEMI')?'is-final':stage.includes('SEMI')?'is-semi':''}`} key={stage}><header><strong>{stage}</strong><span>{rows.filter(r=>r.stage===stage&&r.status==='COMPLETED').length}/{rows.filter(r=>r.stage===stage).length}</span></header>{rows.filter(r=>r.stage===stage).map(r=><div className={`archive-bracket-match ${r.status==='COMPLETED'?'complete':''}`} key={r.id}><div><span>{r.p1?.name||FALLBACK_NAME('blue')}</span><b>{r.score?.split('—')[0]||'—'}</b></div><div><span>{r.p2?.name||FALLBACK_NAME('red')}</span><b>{r.score?.split('—')[1]||'—'}</b></div><small>{r.status}{r.winner?` · ${r.winner.toUpperCase()}`:''}</small></div>)}</div>)}</div></section>}
   {tab==='PLAYERS'&&<section className="archive-grid-2"><div className="archive-panel"><div className="archive-panel-title"><Users/> PLAYER ROSTER · {players.length}</div><div className="archive-roster">{players.map((p:any,i)=><div className="archive-roster-row" key={p.id||`${p.name}-${i}`}><MiniPlayer p={p} side={i%2?'red':'blue'}/><span>{p.club||'—'}</span><b>{p.nationality?getCountryFlag(p.nationality):'—'}</b></div>)}</div></div><div className="archive-panel"><div className="archive-panel-title"><Trophy/> CLUBS · {clubs.length}</div><div className="archive-clubs">{clubs.map((c,i)=><div key={c}><span>{String(i+1).padStart(2,'0')}</span><strong>{c}</strong><b>{players.filter((p:any)=>p.club===c).length}</b></div>)}</div></div></section>}
   <footer className="archive-footer"><span><Lock size={12}/> Completed matches are immutable from this control layer.</span><span><Video size={12}/> Replay history is derived from recorded match events.</span><span><WifiOff size={12}/> Local-first archive remains available offline.</span></footer>
   </>}
  </div>
 </main>
}
function Health({label,ok,value}:{label:string;ok:boolean;value:string}){return <div className={`archive-health ${ok?'ok':'warn'}`}><div>{ok?<CheckCircle2/>:<WifiOff/>}<span>{label}</span></div><strong>{value}</strong></div>}
function ListOrderedIcon(props:any){return <div {...props}><span className="archive-list-icon">☷</span></div>}
