import React,{useEffect,useRef,useState} from 'react';
import {Monitor,MonitorOff,ChevronDown,Check,Radio,LayoutDashboard,CalendarClock} from 'lucide-react';
import {useI18n} from '@/lib/i18n';
import type {ElectronDisplay,PublicDisplayStatus} from '@/types/electron';
import {getBroadcastDisplayConfig,setBroadcastDisplayConfig,BroadcastDisplayMode} from '@/lib/broadcast-display';

export default function PublicDisplayControl(){
 const{t,lang}=useI18n();const api=typeof window!=='undefined'?window.electronAPI:undefined;
 const[open,setOpen]=useState(false),[displays,setDisplays]=useState<ElectronDisplay[]>([]),[status,setStatus]=useState<PublicDisplayStatus>({open:false,displayId:null,openDisplays:[]}),[selectedId,setSelectedId]=useState<number|null>(null),[configs,setConfigs]=useState<Record<number,string>>({}),[prompt,setPrompt]=useState<ElectronDisplay|null>(null);const ref=useRef<HTMLDivElement>(null);
 const load=async()=>{if(!api)return;const[d,s,sel]=await Promise.all([api.getDisplays(),api.getPublicDisplayStatus(),api.getSelectedDisplay()]);setDisplays(d);setStatus(s);setSelectedId(sel.selectedDisplayId);const c:Record<number,string>={};d.filter(x=>!x.isPrimary).forEach(x=>c[x.id]=getBroadcastDisplayConfig(x.id).mode);setConfigs(c);};
 useEffect(()=>{if(!api)return;load();const offD=api.onDisplaysChanged(()=>load()),offS=api.onPublicDisplayStatusChanged(setStatus),offN=api.onNewExternalDisplay(d=>{setPrompt(d);load();});return()=>{offD();offS();offN();};},[api]);
 useEffect(()=>{if(!open)return;const f=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',f);return()=>document.removeEventListener('mousedown',f);},[open]);
 if(!api)return null;const ext=displays.filter(d=>!d.isPrimary);
 const setMode=(id:number,mode:BroadcastDisplayMode)=>{setBroadcastDisplayConfig(id,{...getBroadcastDisplayConfig(id),mode});setConfigs(v=>({...v,[id]:mode}));};
 const setMat=(id:number,mat:number)=>setBroadcastDisplayConfig(id,{...getBroadcastDisplayConfig(id),matNumber:mat});
 const openDisplay=async(id:number)=>{await api.selectDisplay(id);await api.openPublicDisplay(id);setSelectedId(id);await load();};
 const confirmPrompt=(mode:BroadcastDisplayMode)=>{if(!prompt)return;setMode(prompt.id,mode);setSelectedId(prompt.id);setPrompt(null);openDisplay(prompt.id);};
 const labelMode=(m:string)=>m==='mat_announcer'?(lang==='ar'?'إعلان البساط':'Mat Announcer'):m==='upcoming'?(lang==='ar'?'المباريات القادمة':'Upcoming Matches'):(lang==='ar'?'المباراة الحية':'Live Match');
 return <div className="relative shrink-0" ref={ref}>
  <button onClick={()=>setOpen(v=>!v)} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-semibold bg-[hsl(var(--secondary))]/50 hover:bg-[hsl(var(--secondary))] transition-colors"><span className={`w-1.5 h-1.5 rounded-full ${status.open?'bg-emerald-500':'bg-white/30'}`}/><Monitor size={12}/>{t('publicDisplayLabel')}<ChevronDown size={11}/></button>
  {open&&<div className="absolute end-0 top-full mt-1.5 w-[360px] rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-xl z-50 overflow-hidden">
   <div className="p-3 border-b border-[hsl(var(--border))]"><b className="text-xs">{lang==='ar'?'الشاشات الخارجية':'EXTERNAL DISPLAYS'}</b><div className="text-[10px] text-white/45 mt-1">{lang==='ar'?'لكل تلفاز إعداد مستقل ويمكن تغييره بدون فصل التلفاز.':'Each TV has an independent broadcast mode and can be changed without disconnecting it.'}</div></div>
   {ext.length===0?<div className="p-4 text-[11px] text-white/45">{t('noExternalDisplay')}</div>:<div className="p-2 space-y-2">{ext.map(d=>{const cfg=getBroadcastDisplayConfig(d.id);const isOpen=status.openDisplays?.includes(d.id);return <div key={d.id} className="rounded-xl border border-white/10 bg-white/[.02] p-2.5">
    <div className="flex items-center gap-2"><Monitor size={13}/><span className="text-xs font-black flex-1">{d.label}</span>{isOpen&&<span className="text-[9px] text-emerald-400">{lang==='ar'?'مفتوحة':'OPEN'}</span>}</div>
    <div className="grid grid-cols-3 gap-1.5 mt-2"><button onClick={()=>setMode(d.id,'scoreboard')} className={`px-1 py-2 rounded-lg text-[9px] font-bold border ${cfg.mode==='scoreboard'?'border-primary text-primary bg-primary/10':'border-white/10 text-white/50'}`}><LayoutDashboard size={11} className="inline me-1"/>{lang==='ar'?'حالية':'Live Match'}</button><button onClick={()=>setMode(d.id,'mat_announcer')} className={`px-1 py-2 rounded-lg text-[9px] font-bold border ${cfg.mode==='mat_announcer'?'border-yellow-400 text-yellow-300 bg-yellow-400/10':'border-white/10 text-white/50'}`}><Radio size={11} className="inline me-1"/>{lang==='ar'?'البساط':'Mat Announcer'}</button><button onClick={()=>setMode(d.id,'upcoming')} className={`px-1 py-2 rounded-lg text-[9px] font-bold border ${cfg.mode==='upcoming'?'border-blue-400 text-blue-300 bg-blue-400/10':'border-white/10 text-white/50'}`}><CalendarClock size={11} className="inline me-1"/>{lang==='ar'?'قادمة':'Upcoming'}</button></div>
    {cfg.mode!=='scoreboard'&&<div className="mt-2 flex items-center gap-2"><span className="text-[9px] text-white/45">{lang==='ar'?'البساط':'MAT'}</span><select value={cfg.matNumber||1} onChange={e=>setMat(d.id,Number(e.target.value))} className="flex-1 rounded-lg bg-black/30 border border-white/10 px-2 py-1.5 text-[10px]">{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{`MAT ${String(i+1).padStart(2,'0')}`}</option>)}</select></div>}
    <div className="mt-2 flex gap-1.5"><button onClick={()=>openDisplay(d.id)} className="flex-1 rounded-lg bg-primary/15 text-primary border border-primary/30 px-2 py-1.5 text-[10px] font-black"><Monitor size={11} className="inline me-1"/>{isOpen?(lang==='ar'?'تطبيق':'Apply'):(lang==='ar'?'بث الآن':'Broadcast')}</button>{isOpen&&<button onClick={()=>api.closePublicDisplay(d.id).then(load)} className="rounded-lg bg-red-500/10 text-red-300 border border-red-500/20 px-2 py-1.5 text-[10px] font-black"><MonitorOff size={11}/></button>}</div>
    <div className="text-[9px] text-white/35 mt-1">{labelMode(cfg.mode)}{cfg.mode!=='scoreboard'?` · MAT ${cfg.matNumber||1}`:''}</div>
   </div>})}</div>}
  </div>}
  {prompt&&<div className="fixed inset-0 z-[300] bg-black/70 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl border border-yellow-400/40 bg-[#0b0c12] p-5 shadow-2xl"><div className="flex items-center gap-2 text-yellow-300 font-black text-sm"><Monitor size={18}/>{lang==='ar'?'تم اكتشاف شاشة جديدة':'NEW DISPLAY CONNECTED'}</div><p className="text-xs text-white/60 mt-2">{prompt.label}</p><h3 className="text-sm font-black text-white mt-4">{lang==='ar'?'ماذا تريد أن تبث في هذه التلفاز؟':'What do you want to broadcast on this TV?'}</h3><div className="grid gap-2 mt-3"><button onClick={()=>confirmPrompt('scoreboard')} className="rounded-xl border border-primary/30 bg-primary/10 p-3 text-start text-xs font-bold">{lang==='ar'?'المباراة الحالية — النقاط والوقت والإنذارات وكل التفاصيل':'Live Match — score, timer, warnings and full live details'}</button><button onClick={()=>confirmPrompt('mat_announcer')} className="rounded-xl border border-yellow-400/30 bg-yellow-400/10 p-3 text-start text-xs font-bold">{lang==='ar'?'المباراة الحالية + المباريات القادمة للبساط':'Mat Announcer — current + upcoming matches'}</button><button onClick={()=>confirmPrompt('upcoming')} className="rounded-xl border border-blue-400/30 bg-blue-400/10 p-3 text-start text-xs font-bold">{lang==='ar'?'المباريات القادمة فقط':'Upcoming Matches only'}</button></div><button onClick={()=>setPrompt(null)} className="mt-3 w-full rounded-lg border border-white/10 py-2 text-xs text-white/50">{lang==='ar'?'إلغاء':'Cancel'}</button></div></div>}
 </div>
}
