import React,{useState} from 'react';
import { useAccessControl, UserRole } from '@/context/AccessControlContext';
import { logAudit } from '@/lib/audit-log';
import { createSalt, hashPin, secureGet, secureSet } from '@/lib/local-auth';
import { toast } from 'sonner';

type User={id:string;name:string;role:UserRole;pinHash:string;pinSalt:string;active:boolean};
const SECURE_KEY='wab-tkd-users-secure-v1';
export default function TournamentUsersPanel(){const {isAdmin}=useAccessControl();const [users,setUsers]=useState<User[]>([]);
 React.useEffect(()=>{let alive=true;(async()=>{try{const raw=await secureGet(SECURE_KEY);if(raw){const parsed=JSON.parse(raw);if(alive&&Array.isArray(parsed))setUsers(parsed);}else{const legacy=localStorage.getItem('wab-tkd-users-v1');if(legacy){const parsed=JSON.parse(legacy);if(Array.isArray(parsed)){await secureSet(SECURE_KEY,JSON.stringify(parsed));localStorage.removeItem('wab-tkd-users-v1');if(alive)setUsers(parsed);}}}}catch{}})();return()=>{alive=false}},[]);const [name,setName]=useState('');const [role,setRole]=useState<UserRole>('REFEREE');const [pin,setPin]=useState('');
 const save=async(next:User[])=>{setUsers(next);await secureSet(SECURE_KEY,JSON.stringify(next));};
 const add=async()=>{if(!name.trim()||!/^\d{4,8}$/.test(pin))return;const salt=createSalt();const pinHash=await hashPin(pin,salt);const u={id:crypto.randomUUID(),name:name.trim(),role,pinHash,pinSalt:salt,active:true};await save([...users,u]);setName('');setPin('');logAudit('user_created',`Created ${role} user ${name.trim()}`);toast.success('User created');};
 if(!isAdmin)return <div className="text-xs text-muted-foreground">ADMIN permission required.</div>;
 return <div className="space-y-3"><div className="grid md:grid-cols-4 gap-2"><input className="w-full rounded-lg bg-black/20 border border-white/10 px-3 py-2 text-xs" placeholder="User name" value={name} onChange={e=>setName(e.target.value)}/><select className="w-full rounded-lg bg-black/20 border border-white/10 px-3 py-2 text-xs" value={role} onChange={e=>setRole(e.target.value as UserRole)}><option>REFEREE</option><option>SUPERVISOR</option><option>ADMIN</option></select><input className="w-full rounded-lg bg-black/20 border border-white/10 px-3 py-2 text-xs" placeholder="4–8 digit PIN" value={pin} maxLength={8} inputMode="numeric" type="password" onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,8))}/><button className="rounded-lg bg-[hsl(var(--gold))] text-black px-3 py-2 text-[9px] font-black" onClick={add}>ADD USER</button></div><div className="space-y-2">{users.map(u=><div key={u.id} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><div><div className="font-black text-xs">{u.name}</div><div className="text-[9px] text-muted-foreground">{u.role} · PIN HASHED</div></div><button className="px-3 py-1 rounded bg-white/5 text-[9px] font-black" onClick={async()=>save(users.map(x=>x.id===u.id?{...x,active:!x.active}:x))}>{u.active?'ACTIVE':'DISABLED'}</button></div>)}</div></div>}
