// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key';

// True only when real credentials are present. When false, cloud-dependent
// features (side-judge sync, tournament cloud save, etc.) should be treated
// as unavailable, but the app itself must never crash on startup because of
// this — a packaged Electron build has no .env file unless one was baked in
// at build time, and the previous behavior (throwing at import time) blacked
// out the entire app before React could even render.
export const isSupabaseConfigured = Boolean(
  import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ---------------------------------------------------------------------------
// Supabase production authentication
// ---------------------------------------------------------------------------
// Production builds do NOT bootstrap anonymous sessions. The final RLS
// migration requires a real authenticated user carrying app_metadata.role.
// Local/offline tournament operation remains available when cloud auth is not
// configured. Anonymous sessions can be explicitly enabled only for a
// controlled development environment with VITE_SUPABASE_ALLOW_ANONYMOUS=true.
const allowAnonymous = String(import.meta.env.VITE_SUPABASE_ALLOW_ANONYMOUS || '').toLowerCase() === 'true';

if (isSupabaseConfigured && allowAnonymous) {
  supabase.auth.getSession().then(({ data }) => {
    if (!data.session) {
      supabase.auth.signInAnonymously().then(({ error }) => {
        if (error) console.warn('[supabase] anonymous development session failed:', error.message);
      });
    }
  });
}
